%YAML 1.1
---
version: '>=2.3.0 || @head'
export: |

    project "Date"

        kind "StaticLib"

        zpm.export [[
            includedirs "include"

            cppdialect "C++11"
        ]]
...
---
version: '>0.0.0'
export: |

    project "Date"

        kind "StaticLib"

        zpm.export [[
            includedirs "."

            cppdialect "C++11"
        ]]
...